/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CodeSnippetService } from "../codeSnippet.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CodeSnippetCreateInput } from "./CodeSnippetCreateInput";
import { CodeSnippet } from "./CodeSnippet";
import { CodeSnippetFindManyArgs } from "./CodeSnippetFindManyArgs";
import { CodeSnippetWhereUniqueInput } from "./CodeSnippetWhereUniqueInput";
import { CodeSnippetUpdateInput } from "./CodeSnippetUpdateInput";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { CommentWhereUniqueInput } from "../../comment/base/CommentWhereUniqueInput";
import { FeedbackFindManyArgs } from "../../feedback/base/FeedbackFindManyArgs";
import { Feedback } from "../../feedback/base/Feedback";
import { FeedbackWhereUniqueInput } from "../../feedback/base/FeedbackWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CodeSnippetControllerBase {
  constructor(
    protected readonly service: CodeSnippetService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CodeSnippet })
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCodeSnippet(
    @common.Body() data: CodeSnippetCreateInput
  ): Promise<CodeSnippet> {
    return await this.service.createCodeSnippet({
      data: data,
      select: {
        codeContent: true,
        codeName: true,
        createdAt: true,
        description: true,
        id: true,
        owner: true,
        programmingLanguage: true,
        updatedAt: true,
        visibilityStatus: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CodeSnippet] })
  @ApiNestedQuery(CodeSnippetFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async codeSnippets(@common.Req() request: Request): Promise<CodeSnippet[]> {
    const args = plainToClass(CodeSnippetFindManyArgs, request.query);
    return this.service.codeSnippets({
      ...args,
      select: {
        codeContent: true,
        codeName: true,
        createdAt: true,
        description: true,
        id: true,
        owner: true,
        programmingLanguage: true,
        updatedAt: true,
        visibilityStatus: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CodeSnippet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async codeSnippet(
    @common.Param() params: CodeSnippetWhereUniqueInput
  ): Promise<CodeSnippet | null> {
    const result = await this.service.codeSnippet({
      where: params,
      select: {
        codeContent: true,
        codeName: true,
        createdAt: true,
        description: true,
        id: true,
        owner: true,
        programmingLanguage: true,
        updatedAt: true,
        visibilityStatus: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CodeSnippet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCodeSnippet(
    @common.Param() params: CodeSnippetWhereUniqueInput,
    @common.Body() data: CodeSnippetUpdateInput
  ): Promise<CodeSnippet | null> {
    try {
      return await this.service.updateCodeSnippet({
        where: params,
        data: data,
        select: {
          codeContent: true,
          codeName: true,
          createdAt: true,
          description: true,
          id: true,
          owner: true,
          programmingLanguage: true,
          updatedAt: true,
          visibilityStatus: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CodeSnippet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCodeSnippet(
    @common.Param() params: CodeSnippetWhereUniqueInput
  ): Promise<CodeSnippet | null> {
    try {
      return await this.service.deleteCodeSnippet({
        where: params,
        select: {
          codeContent: true,
          codeName: true,
          createdAt: true,
          description: true,
          id: true,
          owner: true,
          programmingLanguage: true,
          updatedAt: true,
          visibilityStatus: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/comments")
  @ApiNestedQuery(CommentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Comment",
    action: "read",
    possession: "any",
  })
  async findComments(
    @common.Req() request: Request,
    @common.Param() params: CodeSnippetWhereUniqueInput
  ): Promise<Comment[]> {
    const query = plainToClass(CommentFindManyArgs, request.query);
    const results = await this.service.findComments(params.id, {
      ...query,
      select: {
        author: true,

        codeSnippet: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "update",
    possession: "any",
  })
  async connectComments(
    @common.Param() params: CodeSnippetWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        connect: body,
      },
    };
    await this.service.updateCodeSnippet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "update",
    possession: "any",
  })
  async updateComments(
    @common.Param() params: CodeSnippetWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        set: body,
      },
    };
    await this.service.updateCodeSnippet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "update",
    possession: "any",
  })
  async disconnectComments(
    @common.Param() params: CodeSnippetWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        disconnect: body,
      },
    };
    await this.service.updateCodeSnippet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/feedbacks")
  @ApiNestedQuery(FeedbackFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Feedback",
    action: "read",
    possession: "any",
  })
  async findFeedbacks(
    @common.Req() request: Request,
    @common.Param() params: CodeSnippetWhereUniqueInput
  ): Promise<Feedback[]> {
    const query = plainToClass(FeedbackFindManyArgs, request.query);
    const results = await this.service.findFeedbacks(params.id, {
      ...query,
      select: {
        author: true,

        codeSnippet: {
          select: {
            id: true,
          },
        },

        comment: true,
        createdAt: true,
        id: true,
        rating: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/feedbacks")
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "update",
    possession: "any",
  })
  async connectFeedbacks(
    @common.Param() params: CodeSnippetWhereUniqueInput,
    @common.Body() body: FeedbackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feedbacks: {
        connect: body,
      },
    };
    await this.service.updateCodeSnippet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/feedbacks")
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "update",
    possession: "any",
  })
  async updateFeedbacks(
    @common.Param() params: CodeSnippetWhereUniqueInput,
    @common.Body() body: FeedbackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feedbacks: {
        set: body,
      },
    };
    await this.service.updateCodeSnippet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/feedbacks")
  @nestAccessControl.UseRoles({
    resource: "CodeSnippet",
    action: "update",
    possession: "any",
  })
  async disconnectFeedbacks(
    @common.Param() params: CodeSnippetWhereUniqueInput,
    @common.Body() body: FeedbackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feedbacks: {
        disconnect: body,
      },
    };
    await this.service.updateCodeSnippet({
      where: params,
      data,
      select: { id: true },
    });
  }
}
