/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { CommentUpdateManyWithoutCodeSnippetsInput } from "./CommentUpdateManyWithoutCodeSnippetsInput";
import { Type } from "class-transformer";
import { FeedbackUpdateManyWithoutCodeSnippetsInput } from "./FeedbackUpdateManyWithoutCodeSnippetsInput";
import { EnumCodeSnippetVisibilityStatus } from "./EnumCodeSnippetVisibilityStatus";

@InputType()
class CodeSnippetUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeContent?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeName?: string | null;

  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutCodeSnippetsInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutCodeSnippetsInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutCodeSnippetsInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutCodeSnippetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => FeedbackUpdateManyWithoutCodeSnippetsInput,
  })
  @ValidateNested()
  @Type(() => FeedbackUpdateManyWithoutCodeSnippetsInput)
  @IsOptional()
  @Field(() => FeedbackUpdateManyWithoutCodeSnippetsInput, {
    nullable: true,
  })
  feedbacks?: FeedbackUpdateManyWithoutCodeSnippetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  owner?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  programmingLanguage?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCodeSnippetVisibilityStatus,
  })
  @IsEnum(EnumCodeSnippetVisibilityStatus)
  @IsOptional()
  @Field(() => EnumCodeSnippetVisibilityStatus, {
    nullable: true,
  })
  visibilityStatus?: "Option1" | null;
}

export { CodeSnippetUpdateInput as CodeSnippetUpdateInput };
